/* cmake/config.h.cmake — generated by CMake; do not edit directly */
#ifndef CONFIG_H
#define CONFIG_H

/* Package info */
#define PACKAGE "testdisk"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"
#define TESTDISKDATE "April 2025"

/* GNU extensions */
#define _GNU_SOURCE 1

/* ── Platform ────────────────────────────────────────────────────────────── */
#cmakedefine TARGET_LINUX   1
#cmakedefine TARGET_BSD     1
#cmakedefine TARGET_SOLARIS 1

/* Little-endian: defined when processor stores LSB first */
#cmakedefine TESTDISK_LSB 1

/* ── Optional library support ────────────────────────────────────────────── */
#cmakedefine HAVE_NCURSES    1
#cmakedefine HAVE_LIBEXT2FS  1
#cmakedefine HAVE_LIBCOMM_ERR 1
#cmakedefine HAVE_LIBJPEG    1
#cmakedefine HAVE_LIBNTFS3G  1
#cmakedefine HAVE_LIBNTFS    1
#cmakedefine HAVE_LIBEWF     1
#cmakedefine HAVE_LIBZ       1
#cmakedefine HAVE_LIBUUID    1

/* DFXML log output (enabled by default) */
#define ENABLE_DFXML 1

/* ── Header availability ─────────────────────────────────────────────────── */
#cmakedefine HAVE_BYTESWAP_H           1
#cmakedefine HAVE_DIRENT_H             1
#cmakedefine HAVE_ENDIAN_H             1
#cmakedefine HAVE_ERRNO_H              1
#cmakedefine HAVE_FCNTL_H              1
#cmakedefine HAVE_FEATURES_H           1
#cmakedefine HAVE_GLOB_H               1
#cmakedefine HAVE_ICONV_H              1
#cmakedefine HAVE_LIBGEN_H             1
#cmakedefine HAVE_LIMITS_H             1
#cmakedefine HAVE_LOCALE_H             1
#cmakedefine HAVE_MALLOC_H             1
#cmakedefine HAVE_NCURSES_H            1
#cmakedefine HAVE_NCURSESW_CURSES_H    1
#cmakedefine HAVE_NCURSESW_NCURSES_H   1
#cmakedefine HAVE_PWD_H                1
#cmakedefine HAVE_SETJMP_H             1
#cmakedefine HAVE_SIGNAL_H             1
#cmakedefine HAVE_STDARG_H             1
#cmakedefine HAVE_SYS_DISK_H           1
#cmakedefine HAVE_SYS_IOCTL_H          1
#cmakedefine HAVE_SYS_PARAM_H          1
#cmakedefine HAVE_SYS_SELECT_H         1
#cmakedefine HAVE_SYS_SYSMACROS_H      1
#cmakedefine HAVE_SYS_TIME_H           1
#cmakedefine HAVE_SYS_UTSNAME_H        1
#cmakedefine HAVE_TIME_H               1
#cmakedefine HAVE_UTIME_H              1
#cmakedefine HAVE_ZLIB_H               1
#cmakedefine HAVE_JPEGLIB_H            1
#cmakedefine HAVE_LIBEWF_H             1
#cmakedefine HAVE_UUID_UUID_H          1
#cmakedefine HAVE_EXT2FS_EXT2FS_H      1
#cmakedefine HAVE_EXT2FS_EXT2_FS_H     1
#cmakedefine HAVE_LINUX_FS_H           1
#cmakedefine HAVE_LINUX_HDREG_H        1
#cmakedefine HAVE_LINUX_TYPES_H        1

/* ── Function availability ───────────────────────────────────────────────── */
#cmakedefine HAVE_ATEXIT        1
#cmakedefine HAVE_ATOLL         1
#cmakedefine HAVE_CHDIR         1
#cmakedefine HAVE_CHMOD         1
#cmakedefine HAVE_DIRNAME       1
#cmakedefine HAVE_DUP2          1
#cmakedefine HAVE_EXECV         1
#cmakedefine HAVE_FDATASYNC     1
#cmakedefine HAVE_FSEEKO        1
#cmakedefine HAVE_FSYNC         1
#cmakedefine HAVE_FTELLO        1
#cmakedefine HAVE_FTRUNCATE     1
#cmakedefine HAVE_GETCWD        1
#cmakedefine HAVE_GETEUID       1
#cmakedefine HAVE_GETPWUID      1
#cmakedefine HAVE_ICONV         1
#cmakedefine HAVE_LOCALTIME_R   1
#cmakedefine HAVE_LSTAT         1
#cmakedefine HAVE_MEMALIGN      1
#cmakedefine HAVE_MEMCHR        1
#cmakedefine HAVE_MEMSET        1
#cmakedefine HAVE_MKDIR         1
#cmakedefine HAVE_POSIX_FADVISE 1
#cmakedefine HAVE_POSIX_MEMALIGN 1
#cmakedefine HAVE_PREAD         1
#cmakedefine HAVE_PWRITE        1
#cmakedefine HAVE_READLINK      1
#cmakedefine HAVE_SETENV        1
#cmakedefine HAVE_SETLOCALE     1
#cmakedefine HAVE_SIGACTION     1
#cmakedefine HAVE_SIGNAL        1
#cmakedefine HAVE_SLEEP         1
#cmakedefine HAVE_SNPRINTF      1
#cmakedefine HAVE_STRCASECMP    1
#cmakedefine HAVE_STRCASESTR    1
#cmakedefine HAVE_STRCHR        1
#cmakedefine HAVE_STRDUP        1
#cmakedefine HAVE_STRERROR      1
#cmakedefine HAVE_STRNCASECMP   1
#cmakedefine HAVE_STRPTIME      1
#cmakedefine HAVE_STRRCHR       1
#cmakedefine HAVE_STRSTR        1
#cmakedefine HAVE_STRTOL        1
#cmakedefine HAVE_STRTOUL       1
#cmakedefine HAVE_STRTOULL      1
#cmakedefine HAVE_UNAME         1
#cmakedefine HAVE_UTIME         1
#cmakedefine HAVE_UUID_CREATE   1
#cmakedefine HAVE_UUID_GENERATE 1
#cmakedefine HAVE_VSNPRINTF     1
#cmakedefine HAVE_WCTOMB        1

/* ── Fortify source (glibc bounds-checking) ──────────────────────────────── */
#ifndef _FORTIFY_SOURCE
#define _FORTIFY_SOURCE 2
#endif

#endif /* CONFIG_H */
